// Writes src/data.ts from the oracle: the limits and the MIME tables are the crate's, so the
// package carries them as generated source and never as a hand-typed copy.
//
//   node qa/data.mjs [--check]

import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { flags } from "./lib.mjs";
import { ask } from "./oracle.mjs";

const args = flags({ check: { type: "boolean", default: false } });

const [{ ok: data }] = await ask([{ op: "data", now: 0, last: 0 }]);
const literal = (value) => JSON.stringify(value, null, 2);
// The same literal, frozen at every level: a caller cannot change a limit under the package
const frozen = (value, indent = "") => {
  if (Array.isArray(value)) return `/* @__PURE__ */ Object.freeze([${value.map((item) => frozen(item)).join(", ")}] as const)`;
  if (typeof value !== "object" || value === null) return JSON.stringify(value);
  const members = Object.entries(value).map(([key, member]) => `${indent}  ${key}: ${frozen(member, `${indent}  `)},`);
  return `Object.freeze({\n${members.join("\n")}\n${indent}})`;
};
const source = `// Generated by qa/data.mjs from the crate's constants. Do not edit.

/**
 * The data model's limits, in the units their names say: what a builder refuses past.
 *
 * @example
 * \`\`\`ts
 * import { limits } from "pubky-social-specs";
 * console.log(limits.postNoteContentMaxLength, limits.maxFileSizeBytes);
 * \`\`\`
 */
export const limits = /* @__PURE__ */ ${frozen(data.limits)};

export const MIME_TO_EXT = ${frozen(data.mimeToExt)};

/**
 * The media types the package maps to an extension; any other is stored as \`.bin\`.
 *
 * @example
 * \`\`\`ts
 * import { validMimeTypes } from "pubky-social-specs";
 * console.log(validMimeTypes.includes("image/png"));
 * \`\`\`
 */
export const validMimeTypes = ${frozen(data.validMimeTypes)};

/**
 * Why the migration leaves a 0.x object behind: the keys of a report's \`skipped\`.
 *
 * @example
 * \`\`\`ts
 * import { skipReasons } from "pubky-social-specs/migration";
 * console.log(skipReasons.join(", "));
 * \`\`\`
 */
export const skipReasons = ${frozen(data.skipReasons)};

/**
 * The revision of the migration's transforms: a flag recorded under a lower one is walked again.
 *
 * @example
 * \`\`\`ts
 * import { transformRev } from "pubky-social-specs/migration";
 * console.log(transformRev);
 * \`\`\`
 */
export const transformRev: number = ${data.transformRev};

/**
 * The code points the reference spells as \\u{..} when an error quotes text, as inclusive
 * ranges laid end to end. It follows the Unicode tables the reference was built with.
 */
export const DEBUG_ESCAPED: readonly number[] = [${data.debugEscaped.flat().join(",")}];
`;
// The extensions a media file name may carry are the mapped ones and the fallback; the package
// derives them, so a reference that ever stripped another one has to be met here first
const derived = [...new Set([...data.mimeToExt.map(([, ext]) => ext), "bin"])].sort();
if (JSON.stringify(derived) !== JSON.stringify([...data.stripSet].sort())) {
  console.error(`the reference strips ${data.stripSet.join(", ")}, not the mapped extensions and bin`);
  process.exit(1);
}
const file = fileURLToPath(new URL("../src/data.ts", import.meta.url));
if (args.check) {
  if (fs.readFileSync(file, "utf8") !== source) {
    console.error("src/data.ts is stale: run node qa/data.mjs");
    process.exit(1);
  }
} else fs.writeFileSync(file, source);
