// Writes src/data.ts from the oracle: the limits and the MIME tables are the crate's, so the
// package carries them as generated source and never as a hand-typed copy.
//
//   node qa/data.mjs [--check]

import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { flags } from "./lib.mjs";
import { ask } from "./oracle.mjs";

const args = flags({ check: { type: "boolean", default: false } });

const [{ ok: data }] = await ask([{ op: "data", now: 0, last: 0 }]);
const literal = (value) => JSON.stringify(value, null, 2);
// The same literal, frozen at every level: a caller cannot change a limit under the package
const frozen = (value, indent = "") => {
  if (Array.isArray(value)) return `/* @__PURE__ */ Object.freeze([${value.map((item) => frozen(item)).join(", ")}] as const)`;
  if (typeof value !== "object" || value === null) return JSON.stringify(value);
  const members = Object.entries(value).map(([key, member]) => `${indent}  ${key}: ${frozen(member, `${indent}  `)},`);
  return `Object.freeze({\n${members.join("\n")}\n${indent}})`;
};
// What each limit bounds; the unit comes from the name. A limit the crate adds without a line
// here fails the build, so every member a caller hovers says what it measures
const LIMIT_DOCS = {
  articleBodyMaxLength: "The longest article body",
  articleContentMaxLength: "The longest `content` of an article post, the whole envelope as text",
  articleTitleMaxLength: "The longest article title",
  attachmentAltMaxLength: "The longest `alt` text of an attachment",
  attachmentNameMaxLength: "The longest `name` of an attachment",
  bookmarkTargetUriMaxBytes: "The longest target a primary bookmark spells in its filename; a longer one takes the overflow form, `~{hash}`",
  collectionContentMaxLength: "The longest `content` of a collection post, the whole envelope as text",
  collectionDescriptionMaxLength: "The longest collection description",
  collectionItemNoteMaxLength: "The longest note on a collection item",
  collectionItemsMaxCount: "The most items in a collection",
  collectionNameMaxLength: "The longest collection name",
  collectionNameMinLength: "The shortest collection name",
  feedIconMaxLength: "The longest feed icon name",
  feedNameMaxLength: "The longest feed name",
  feedTagsMaxCount: "The most labels in a feed's `tags`, and in its `domain_tags`",
  imageUrlMaxLength: "The longest profile `image` and article or collection `cover_image`",
  maxFileSizeBytes: "The largest media file, 100 MiB",
  objectMaxBytes: "The largest stored object other than a post, as stored",
  postAllowedAttachmentProtocols: "The schemes an attachment URI may have",
  postAttachmentsMaxCount: "The most attachments on a post",
  postMaxBytes: "The largest stored post, as stored",
  postNoteContentMaxLength: "The longest `content` of a post of any kind but an article or a collection",
  postSlugMaxLength: "The longest slug of a post version",
  referenceUriMaxLength: "The longest reference: a `parent`, an `embed`, a `lock`, an attachment or a collection item",
  tagInvalidChars: "The characters a tag label may not hold",
  tagLabelMaxLength: "The longest tag label",
  tagLabelMinLength: "The shortest tag label",
  userBioMaxLength: "The longest profile bio",
  userLinkTitleMaxLength: "The longest title of a profile link",
  userLinkUrlMaxLength: "The longest URL of a profile link",
  userLinksMaxCount: "The most links on a profile",
  userNameMaxLength: "The longest profile name",
  userNameMinLength: "The shortest profile name",
  userStatusMaxLength: "The longest profile status",
};
const unitOf = (name) => (name.endsWith("Bytes") ? "bytes" : name.endsWith("Count") ? "items" : name.endsWith("Length") ? "code points" : null);
const undocumented = Object.keys(data.limits).filter((name) => !Object.hasOwn(LIMIT_DOCS, name));
if (undocumented.length > 0) {
  console.error(`limits with no line in qa/data.mjs LIMIT_DOCS: ${undocumented.join(", ")}`);
  process.exit(1);
}
const limitsSource = `Object.freeze({\n${Object.entries(data.limits)
  .map(([name, value]) => {
    const unit = unitOf(name);
    return `  /** ${LIMIT_DOCS[name]}${unit === null ? "." : `, in ${unit}: ${value}.`} */\n  ${name}: ${frozen(value, "  ")},`;
  })
  .join("\n")}\n})`;

const source = `// Generated by qa/data.mjs from the crate's constants. Do not edit.

/**
 * The data model's limits, in the units their names say: code points for a \`Length\`, bytes for
 * \`Bytes\`, items for a \`Count\`. A builder, a validator and \`decodeObject\` refuse past them
 * with a \`ValidationError\` whose \`code\` is \`length\`, \`size\` or \`count\` and whose \`limit\`
 * is the value here.
 *
 * @example
 * \`\`\`ts
 * import { limits } from "pubky-social-specs";
 * console.log(limits.postNoteContentMaxLength, limits.maxFileSizeBytes);
 * \`\`\`
 */
export const limits = /* @__PURE__ */ ${limitsSource};

export const MIME_TO_EXT = ${frozen(data.mimeToExt)};

/**
 * The media types the data model names. Most map to an extension; \`application/octet-stream\`,
 * \`application/x-www-form-urlencoded\` and \`multipart/form-data\` map to \`.bin\`, as does any
 * type not listed. The table is in docs/reference.md.
 *
 * @example
 * \`\`\`ts
 * import { validMimeTypes } from "pubky-social-specs";
 * console.log(validMimeTypes.includes("image/png"));
 * \`\`\`
 */
export const validMimeTypes = ${frozen(data.validMimeTypes)};

/**
 * Why the migration leaves a 0.x object behind: the keys of a report's \`skipped\`.
 *
 * @example
 * \`\`\`ts
 * import { skipReasons } from "pubky-social-specs/migration";
 * console.log(skipReasons.join(", "));
 * \`\`\`
 */
export const skipReasons = ${frozen(data.skipReasons)};

/**
 * The revision of the migration's transforms: a flag recorded under a lower one is walked again.
 *
 * @example
 * \`\`\`ts
 * import { transformRev } from "pubky-social-specs/migration";
 * console.log(transformRev);
 * \`\`\`
 */
export const transformRev: number = ${data.transformRev};

/**
 * The code points the reference spells as \\u{..} when an error quotes text, as inclusive
 * ranges laid end to end. It follows the Unicode tables the reference was built with.
 */
export const DEBUG_ESCAPED: readonly number[] = [${data.debugEscaped.flat().join(",")}];
`;
// The extensions a media file name may carry are the mapped ones and the fallback; the package
// derives them, so a reference that ever stripped another one has to be met here first
const derived = [...new Set([...data.mimeToExt.map(([, ext]) => ext), "bin"])].sort();
if (JSON.stringify(derived) !== JSON.stringify([...data.stripSet].sort())) {
  console.error(`the reference strips ${data.stripSet.join(", ")}, not the mapped extensions and bin`);
  process.exit(1);
}
const file = fileURLToPath(new URL("../src/data.ts", import.meta.url));
if (args.check) {
  if (fs.readFileSync(file, "utf8") !== source) {
    console.error("src/data.ts is stale: run node qa/data.mjs");
    process.exit(1);
  }
} else fs.writeFileSync(file, source);
