// Writes src/data.ts from the oracle: the limits and the MIME tables are the crate's, so the
// package carries them as generated source and never as a hand-typed copy.
//
//   node qa/data.mjs [--check]

import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { ask } from "./oracle.mjs";

const [{ ok: data }] = await ask([{ op: "data", now: 0, last: 0 }]);
const literal = (value) => JSON.stringify(value, null, 2);
const source = `// Generated by qa/data.mjs from the crate's constants. Do not edit.

export const limits = ${literal(data.limits)} as const;

export const MIME_TO_EXT: ReadonlyArray<readonly [string, string]> = ${literal(data.mimeToExt)};

export const STRIP_SET: readonly string[] = ${literal(data.stripSet)};

export const validMimeTypes: readonly string[] = ${literal(data.validMimeTypes)};

/**
 * The code points the reference spells as \\u{..} when an error quotes text, as inclusive
 * ranges laid end to end. It follows the Unicode tables the reference was built with.
 */
export const DEBUG_ESCAPED: readonly number[] = [${data.debugEscaped.flat().join(",")}];
`;
const file = fileURLToPath(new URL("../src/data.ts", import.meta.url));
if (process.argv.includes("--check")) {
  if (fs.readFileSync(file, "utf8") !== source) {
    console.error("src/data.ts is stale: run node qa/data.mjs");
    process.exit(1);
  }
} else fs.writeFileSync(file, source);
