// Generated by qa/data.mjs from the crate's constants. Do not edit.

export const limits = {
  "articleBodyMaxLength": 50000,
  "articleContentMaxLength": 104000,
  "articleTitleMaxLength": 100,
  "attachmentAltMaxLength": 1000,
  "attachmentNameMaxLength": 255,
  "bookmarkTargetUriMaxBytes": 187,
  "collectionContentMaxLength": 40000,
  "collectionDescriptionMaxLength": 500,
  "collectionItemNoteMaxLength": 1000,
  "collectionItemsMaxCount": 100,
  "collectionNameMaxLength": 100,
  "collectionNameMinLength": 1,
  "feedIconMaxLength": 50,
  "feedNameMaxLength": 100,
  "feedTagsMaxCount": 5,
  "imageUrlMaxLength": 300,
  "maxFileSizeBytes": 104857600,
  "objectMaxBytes": 65536,
  "postAllowedAttachmentProtocols": [
    "pubky",
    "http",
    "https"
  ],
  "postAttachmentsMaxCount": 10,
  "postMaxBytes": 524288,
  "postNoteContentMaxLength": 2000,
  "postSlugMaxLength": 64,
  "referenceUriMaxLength": 1024,
  "tagInvalidChars": [
    ",",
    ":",
    " ",
    "\t",
    "\n",
    "\r"
  ],
  "tagLabelMaxLength": 20,
  "tagLabelMinLength": 1,
  "userBioMaxLength": 160,
  "userLinkTitleMaxLength": 100,
  "userLinkUrlMaxLength": 300,
  "userLinksMaxCount": 5,
  "userNameMaxLength": 50,
  "userNameMinLength": 3,
  "userStatusMaxLength": 50
} as const;

export const MIME_TO_EXT: ReadonlyArray<readonly [string, string]> = [
  [
    "image/jpeg",
    "jpg"
  ],
  [
    "image/png",
    "png"
  ],
  [
    "image/gif",
    "gif"
  ],
  [
    "image/webp",
    "webp"
  ],
  [
    "image/svg+xml",
    "svg"
  ],
  [
    "text/csv",
    "csv"
  ],
  [
    "video/mp4",
    "mp4"
  ],
  [
    "video/mpeg",
    "mpeg"
  ],
  [
    "audio/mpeg",
    "mp3"
  ],
  [
    "audio/wav",
    "wav"
  ],
  [
    "application/pdf",
    "pdf"
  ],
  [
    "application/json",
    "json"
  ],
  [
    "application/xml",
    "xml"
  ],
  [
    "text/xml",
    "xml"
  ],
  [
    "application/zip",
    "zip"
  ],
  [
    "application/javascript",
    "js"
  ],
  [
    "text/css",
    "css"
  ],
  [
    "text/html",
    "html"
  ],
  [
    "text/plain",
    "txt"
  ]
];

export const STRIP_SET: readonly string[] = [
  "bin",
  "css",
  "csv",
  "gif",
  "html",
  "jpg",
  "js",
  "json",
  "mp3",
  "mp4",
  "mpeg",
  "pdf",
  "png",
  "svg",
  "txt",
  "wav",
  "webp",
  "xml",
  "zip"
];

export const validMimeTypes: readonly string[] = [
  "application/javascript",
  "application/json",
  "application/octet-stream",
  "application/pdf",
  "application/x-www-form-urlencoded",
  "application/xml",
  "application/zip",
  "audio/mpeg",
  "audio/wav",
  "image/gif",
  "image/jpeg",
  "image/png",
  "image/svg+xml",
  "image/webp",
  "multipart/form-data",
  "text/css",
  "text/csv",
  "text/html",
  "text/plain",
  "text/xml",
  "video/mp4",
  "video/mpeg"
];
